### PR TITLE
intensify some features

### PR DESCRIPTION
**Pull request by shuying2244**
intensify go to definition
1. for function (#146)
2. for macros (#120)
3. for record (#189)

add features
1. now can go to -include and -include_lib

### CODE REVIEW

**Comment by pgourlain** [comment]
Hi @shuying2244,

thanks for your contribution,

Can you explain, the use case when base name of HrlFile match with  include("basename") or include_lib("...")
- how can I test it, may be I misunderstand something..

regards

**Comment by shuying2244** [comment]
## use case

-- test.erl --
```erlang
-module(test).
-include("common.hrl").
-include_lib("kernel/include/file.hrl").
-compile(export_all).

%% other code

```

File `common.hrl` must exist. It can be in `include/` or the same directory as `test.erl`.

When you use the go to definition for `common`, you can go to file `common.hrl`.  
The same works for `include_lib`

**Comment by pgourlain** [comment]
Hi @shuying2244 ,

Thanks for your reply.
I wrote this file

```erlang
module(moduleA).

-include("utils.hrl").
-include_lib("kernel/include/file.hrl").
% /Users/xxx/Library/Application Support/ErlangInstaller/23.0/lib/kernel-7.0/include/file.hrl

-export([functionA/0,
    function_test/0]).

-compile(export_all).

functionA() ->
    moduleB:functionB(?MYTIMEOUT),
    function_testrecord(#file_info{}),
    ok.

function_testrecord(fileInfo) ->
    
    ok.

function_test() ->
     ok.
```

and I put some logs when match in this peace of code
```erlang
    case LineContents of
        <<"-include(\"", BaseName:Size1/binary, "\").\r">> when Column > 10, Column =< 10 + Size1 ->
            gen_lsp_server:lsp_log("attr hrl match include", []),
            {hrl, HrlFile};
        <<"-include_lib(\"", LongName:Size2/binary, "\").\r">> when Column > 14, Column =< 14 + Size2 ->
            case filename:split(binary_to_list(LongName)) of
                [LibName|Remain] ->
                    case code:lib_dir(LibName) of
                        {error,bad_name} -> undefined;
                        AbsLib ->
                            NativeName = filename:nativename(HrlFile),
                            case filename:nativename(string:join([AbsLib|Remain], "/")) of
                                NativeName -> 
                                    gen_lsp_server:lsp_log("attr hrl match include_lib ~p", [NativeName]),
                                    {hrl, HrlFile};
                                _ -> undefined
                            end
                    end;
                _ -> undefined
            end;
        _ -> undefined
    end
```

and I press F12 on #file_info, or ?MYTIMEOUT, or include or include_lib. And for me this code is never reachable

any idea ?

**Comment by shuying2244** [comment]
Try changing the code to look like this  
Everything will work normal

---

filename: `moduleA.erl`
```erlang
-module(moduleA).

%% -include("utils.hrl").
-include_lib("kernel/include/file.hrl").
% /Users/xxx/Library/Application Support/ErlangInstaller/23.0/lib/kernel-7.0/include/file.hrl

-export([functionA/0,
    function_test/0]).

-compile(export_all).

functionA() ->
    %% moduleB:functionB(?MYTIMEOUT),
    function_testrecord(#file_info{}),
    ok.

function_testrecord(fileInfo) ->
    
    ok.

function_test() ->
     ok.
```
---
### wrong place:
- `module(moduleA).` to `-module(moduleA).`
- file `utils.hrl` not exit
- macro `?MYTIMEOUT` not exit
#### You need to handle this error for the plugin to work properly

**Comment by pgourlain** [comment]
Hi,

Sorry,I'm not clear. 
"utils.hrl" exist on my laptop. And the code that I provide works well. And even I comment your peace of code, "F12" works fine (on my machine).
It's the reason that I ask you about "when this peace of code is usefull".

**Comment by shuying2244** [comment]
Okay, I may have misunderstood you, I thought the plug-in wouldn't work properly after you updated the code.
Actually, what you mean is, under what circumstances are they useful?
In my daily work, sometimes I write `-include_lib("kernel/include/file.hrl").` first, and there are no macros or records in the current file, so if I want to enter `file.hrl`, I need to search for `file.hrl` instead of just jump in.
This is very common, sometimes I copy some `-include("xxx.hrl").` from other files, but I can't remember their contents, and when I want to use them, I need to be able to quickly jump in

**Comment by pgourlain** [comment]
Okay, I understand. Thanks !!

I will refactor a little by using regular expression instead of binary matching. Because if there is a comment at the end of line binary matching doesn't works.

**Pull request merged**
