### PR TITLE
Add features and fix bugs

### PR DESCRIPTION
**Pull request by shuying2244**
## Change log
    1. Optimize the jump experience
        - Now the function jump will be more precise
    2. Fixed some bugs
        - Handled some compile warnings and some compatibility with mismatched errors
    3. New features `gen_msg_use`
        - See Use Cases for more information

### Use Cases
Try using `F12` on `is_open` in `{is_open, List}`  
Support for new features is not limited to `gen_statem`, find more interesting enhancements in use
```erlang
-module(t).
-export([handle_event/4]).

-export([is_open/0, gm_next/0]).

is_open() ->
    List = [1],
    gen_statem:call(?MODULE, {is_open, List}, 1000).

gm_next() ->
    gen_statem:cast(?MODULE, gm_next).

handle_event({call, _From}, {is_open, [_N, _M|_]}, _State, _Data) ->
    keep_state_and_data;

handle_event(cast, gm_next, _State, _Data) ->
    keep_state_and_data.
```

### CODE REVIEW

**Comment by pgourlain** [comment]
Hi @shuying2244,

Nice job !

Can you add this use case in unittests ?
- add test src file into this folder : apps/erlangbridge/test/lsp_navigation_SUITE_data
- add test case in apps/erlangbridge/test/lsp_navigation_SUITE.erl
  - complete navigation_datatests()

**Comment by shuying2244** [comment]
No problem, but not until next week. I'm going to get off work now and enjoy my holiday in the next five days.

**Comment by shuying2244** [comment]
No problem, but not until next week. I'm going to get off work now and enjoy my holiday in the next five days.

**Comment by pgourlain** [comment]
Sure, 
have a nice trip !

**Comment by shuying2244** [comment]
hello,
I've added the unit tests, and I need some instructions on how to validate the examples I've added.

**Comment by pgourlain** [comment]
hello,

I explain in DevelopersReadme.md, just run './rebar3 ct'

**Pull request merged**
